let map,userLocation,userMarker,routeControl,currentFilter='all',satelliteOn=false;const layers={},markers={},tile={};
const ICON={hospital:'🏥',police:'🚔',fire:'🚒',fuel:'⛽',accident:'⚠️',crime:'🚨',military:'🪖'};const LABEL={hospital:'Hospital',police:'Police',fire:'Fire',fuel:'Fuel',accident:'Accident',crime:'Crime',military:'Military'};
function init(){map=L.map('map',{zoomControl:false}).setView([23.94,90.78],10);tile.street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);tile.satellite=L.tileLayer('https://{s}.google.com/vt/lyrs=y&x={x}&y={y}&z={z}',{maxZoom:20,subdomains:['mt0','mt1','mt2','mt3'],attribution:'© Google'});L.control.zoom({position:'bottomright'}).addTo(map);Object.keys(ICON).forEach(t=>layers[t]=L.layerGroup().addTo(map));renderLocations();loadRoutes();bind();locateUser()}
function icon(type,user=false){if(user)return L.divIcon({className:'',html:'<div class="user-dot"></div>',iconSize:[18,18],iconAnchor:[9,9]});return L.divIcon({className:'',html:`<div style="font-size:22px;filter:drop-shadow(0 2px 2px rgba(0,0,0,.35))">${ICON[type]}</div>`,iconSize:[28,28],iconAnchor:[14,14]})}
function renderLocations(){[...EMERGENCY_SERVICES,...RISK_LOCATIONS].forEach(x=>{const m=L.marker([x.lat,x.lng],{icon:icon(x.type)}).bindPopup(`<b>${ICON[x.type]} ${esc(x.name)}</b><div style="font-size:11px;color:#667085">${LABEL[x.type]}</div>${x.details?`<p style="font-size:12px">${esc(x.details)}</p>`:''}`);markers[x.id]=m;layers[x.type].addLayer(m)})}
function loadRoutes(){const s=document.getElementById('routeSelect');PROJECT_ROUTES.forEach(r=>{const o=document.createElement('option');o.value=r.id;o.textContent=r.name;s.appendChild(o)})}
function bind(){document.getElementById('locateBtn').onclick=locateUser;document.getElementById('showRouteBtn').onclick=showProjectRoute;document.getElementById('layersBtn').onclick=()=>document.getElementById('layersPanel').classList.toggle('hidden');document.getElementById('closeLayersBtn').onclick=()=>document.getElementById('layersPanel').classList.add('hidden');document.getElementById('satelliteBtn').onclick=toggleSatellite;document.getElementById('riskBtn').onclick=toggleRisk;document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.type;renderList()});document.querySelectorAll('[data-layer]').forEach(c=>c.onchange=()=>c.checked?map.addLayer(layers[c.dataset.layer]):map.removeLayer(layers[c.dataset.layer]))}
function locateUser(){const st=document.getElementById('locationStatus');if(!navigator.geolocation){st.textContent='Geolocation is not supported.';return}st.textContent='Finding your location…';navigator.geolocation.getCurrentPosition(p=>{userLocation=[p.coords.latitude,p.coords.longitude];if(userMarker)map.removeLayer(userMarker);userMarker=L.marker(userLocation,{icon:icon('',true),zIndexOffset:1000}).addTo(map).bindTooltip('You are here');map.setView(userLocation,13);st.textContent='Your location is active';renderList()},()=>{st.textContent='Location unavailable — allow browser location access.';renderList()},{enableHighAccuracy:true,timeout:10000,maximumAge:30000})}
function dist(a,b){const R=6371,dLat=(b[0]-a[0])*Math.PI/180,dLon=(b[1]-a[1])*Math.PI/180,la1=a[0]*Math.PI/180,la2=b[0]*Math.PI/180,h=Math.sin(dLat/2)**2+Math.sin(dLon/2)**2*Math.cos(la1)*Math.cos(la2);return R*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
function nearest(types=['hospital','police','fire','fuel']){if(!userLocation)return[];return EMERGENCY_SERVICES.filter(x=>types.includes(x.type)).map(x=>({...x,d:dist(userLocation,[x.lat,x.lng])})).sort((a,b)=>a.d-b.d)}
function renderList(){const box=document.getElementById('serviceList');if(!userLocation){box.innerHTML='<div style="padding:10px;color:#667085;font-size:12px">Allow location access to see nearest services.</div>';return}let a=nearest();if(currentFilter!=='all')a=a.filter(x=>x.type===currentFilter);box.innerHTML=a.slice(0,8).map(card).join('')}
function card(x){return `<article class="service-card"><div class="service-top"><div><div class="service-name">${ICON[x.type]} ${esc(x.name)}</div><div class="service-type">${LABEL[x.type]}</div></div><b style="font-size:11px">${x.d.toFixed(1)} km</b></div><div class="meta"><span>Straight-line distance</span></div><div class="actions"><button class="small primary" onclick="routeTo('${x.id}')">Show route</button><button class="small" onclick="navigateTo('${x.id}')">Navigate</button></div></article>`}
function routeTo(id){const x=EMERGENCY_SERVICES.find(s=>s.id===id);if(!x||!userLocation)return;if(routeControl)map.removeControl(routeControl);routeControl=L.Routing.control({waypoints:[L.latLng(...userLocation),L.latLng(x.lat,x.lng)],routeWhileDragging:false,addWaypoints:false,show:false,createMarker:()=>null,lineOptions:{styles:[{color:'#1769aa',weight:6,opacity:.9}]}}).addTo(map);map.setView([x.lat,x.lng],14)}
function navigateTo(id){const x=EMERGENCY_SERVICES.find(s=>s.id===id);if(x)window.open(`https://www.google.com/maps/dir/?api=1&destination=${x.lat},${x.lng}`,'_blank','noopener')}
function showProjectRoute(){const r=PROJECT_ROUTES.find(x=>x.id===document.getElementById('routeSelect').value);if(!r)return;if(routeControl)map.removeControl(routeControl);routeControl=L.Routing.control({waypoints:[L.latLng(...r.origin),L.latLng(...r.destination)],routeWhileDragging:false,addWaypoints:false,show:false,createMarker:(i,w)=>L.marker(w.latLng).bindTooltip(i?'Destination':'Start'),lineOptions:{styles:[{color:'#1769aa',weight:7,opacity:.9}]}}).addTo(map)}

function toggleSatellite(){satelliteOn=!satelliteOn;if(satelliteOn){map.removeLayer(tile.street);tile.satellite.addTo(map)}else{map.removeLayer(tile.satellite);tile.street.addTo(map)}}function toggleRisk(){['accident','crime','military'].forEach(t=>map.hasLayer(layers[t])?map.removeLayer(layers[t]):map.addLayer(layers[t]))}function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}document.addEventListener('DOMContentLoaded',init);
